import turtle
import random
wn=turtle.Screen()
turtle.bgcolor("skyblue")
bear=turtle.Turtle()
bear.pencolor('black')
bear.pensize(4)
bear.speed(50)

def sun():              #creating a sun for the background
    bear.penup()
    bear.goto(-400,200)
    bear.pendown()
    bear.pencolor("yellow")
    bear.begin_fill()
    bear.fillcolor('yellow')
    bear.circle(60)
    bear.end_fill()
    bear.penup()
    bear.goto(-400,260)
    angle = 360 / 12
    for _ in range(12):           # to create sunbeams for the sun 
       bear.forward(100)
       bear.pendown()
       bear.forward(20)
       bear.penup()
       bear.goto(-400,260)
       bear.left(angle)
    
def house():        # a small house for the background
    bear.penup()
    bear.goto(500,100)
    bear.pendown()
    bear.pencolor("black")
    bear.begin_fill()
    bear.fillcolor('brown')
    for _ in range(4):            # to make the base of the house
        bear.forward(300)
        bear.right(90)
    bear.end_fill()
    
    bear.begin_fill()
    bear.fillcolor("brown")
    for _ in range(3): # to make the roof
        bear.forward(300)
        bear.left(360/3)
    bear.end_fill()

    bear.penup()
    bear.goto(650,150)    
    bear.pendown()
    bear.begin_fill()
    bear.fillcolor("white")
    bear.circle(60)
    bear.end_fill()

    bear.penup()
    bear.goto(600,80)
    bear.pendown()
    bear.begin_fill()
    bear.fillcolor("white")
    for _ in range(2):           # the door
        bear.forward(100)
        bear.right(90)
        bear.forward(280)
        bear.right(90)
    bear.end_fill()

def draw_cloud(x, y, size): # to draw clouds
    bear.penup()
    bear.goto(x, y)
    bear.pendown()
    bear.color("white")
    bear.begin_fill()
    for _ in range(5):
        bear.circle(size)
        bear.right(144)
    bear.end_fill()

def background():         # for making a ground 
    bear.penup()
    bear.pencolor("green")
    bear.goto(-800,-145)
    bear.begin_fill()
    bear.fillcolor("green")
    bear.pendown()
    for _ in range(4):
        bear.forward(1600)
        bear.right(90)
    bear.end_fill()
    sun()
    house()

def ballons():       # to create some ballons 
    colors = ['red', 'yellow', 'light green', 'blue', 'violet']          
    for i in range(5):
        a=random.randint(150,250)       #using random function for the postion of ballons
        bear.forward(a)
        bear.begin_fill()
        bear.fillcolor(colors[i])       # giving different colours to the ballons
        bear.circle(60)
        bear.end_fill()
        bear.penup()
        bear.backward(a)
        bear.left(10+i)
        bear.pendown()

def foot():                  #for making foot
        bear.begin_fill()
        bear.fillcolor("black")
        bear.circle(-45)
        bear.end_fill()
        bear.penup()
        bear.right(90)
        bear.forward(45)
        bear.left(80)
        bear.forward(45)
        bear.pendown()
        bear.forward(60)
        bear.penup()         
        bear.left(90)
        bear.forward(45)
        bear.right(90)
        bear.forward(45)
        bear.pendown()
        bear.begin_fill()
        bear.fillcolor('black')
        bear.circle(-45)
        bear.end_fill()
    
def ears():        # to make the ears
    bear.penup()
    bear.goto(0,120)
    bear.right(90)
    for _ in  range(2):   
        bear.forward(90)
        bear.pendown()
        bear.begin_fill()
        bear.fillcolor('black') 
        bear.circle(40)
        bear.end_fill()
        bear.penup()
        bear.goto(0,120)
        bear.left(110)

def eyes():                    # for the eyes
    bear.right(90)
    bear.forward(20)
    bear.pendown()
    bear.circle(20)
    bear.penup()
    bear.right(130)
    bear.forward(40)
    bear.pendown()
    bear.circle(-19)
    bear.begin_fill()
    bear.fillcolor('black')
    bear.circle(-10)
    bear.penup()
    bear.right(185)
    bear.forward(54)
    bear.pendown()
    bear.circle(10)
    bear.end_fill()
            
def nose():                   # for the nose
    bear.penup() 
    bear.left(120)
    bear.forward(40)
    bear.pendown()
    bear.begin_fill()
    bear.fillcolor('maroon') 
    for _ in range(3):
        bear.forward(15)
        bear.left(120)
    bear.end_fill()

def smile():                 # to create a small little smile on the face
    bear.circle(40,80)
    bear.penup()
    bear.left(165)
    bear.forward(70)
    bear.right(180)
    bear.pendown() 
    bear.circle(40,60)
    bear.penup()
    bear.left(160)
    bear.forward(30)
    bear.left(90)
    bear.pendown()
    bear.begin_fill()
    bear.fillcolor("red")
    bear.circle(30,90)
    bear.end_fill()

def blush():                # some pink tint !! like why not ? 
    bear.penup()
    bear.forward(40)
    bear.pendown()
    bear.begin_fill()
    bear.fillcolor("pink")
    bear.pencolor('pink')
    bear.circle(-20)
    bear.penup()
    bear.left(135)
    bear.forward(115)
    bear.pendown()
    bear.circle(20)
    bear.end_fill()

def tie():                 # a tie for the bear
    bear.penup()
    bear.goto(20,0)
    bear.pendown()
    bear.pencolor('dark blue')
    bear.begin_fill()
    bear.fillcolor("dark blue")
    for _ in range(4):
        bear.begin_fill()
        bear.fillcolor("dark blue")
        bear.forward(40)
        bear.left(120)   
    bear.forward(110)
    bear.right(90)
    bear.forward(40)
    bear.right(70)
    bear.forward(30)
    bear.right(70)
    bear.forward(70)
    bear.end_fill()

#__main_
def body():                # creating a body of the bear
    bear.penup() 
    bear.goto(0,0)
    bear.pendown()
    bear.pencolor("black")
    bear.begin_fill()
    bear.fillcolor('white')                        
    bear.circle(95)                    # for the face
    bear.end_fill()
    bear.begin_fill()            
    bear.fillcolor("black")
    bear.circle(94,65)
    bear.right(-237)
    bear.circle(-165,40) 
    bear.circle(-20,180)
    bear.forward(20)
    bear.left(-280)
    bear.circle(235,40)
    bear.left(90)
    bear.circle(-30,120)
    bear.right(90)
    bear.end_fill()
    ballons()          #calling ballon function 
    bear.begin_fill()
    bear.fillcolor("black")
    bear.circle(-70,140)
    bear.right(70)
    bear.forward(20)
    bear.left(40)
    bear.forward(80)
    bear.right(120)
    bear.forward(120)
    bear.end_fill()
    bear.circle(40,60)
    bear.left(100)
    foot()        #calling the foot function
    bear.penup()
    bear.left(290)
    bear.forward(30)
    bear.left(90)
    bear.forward(25)
    bear.pendown()
    bear.circle(50,70)
    ears()            # caliing the functions in the function 
    eyes()
    nose()
    smile()
    blush()
    tie() 
        
background()
body()

wn.exitonclick()